### ISSUE TITLE
docker-compose.override.yml overridden

### ISSUE THREAD

**Issue by sylvainbx** [alexyao2015/BitBetter#1]
Hi,
A suggestion : maybe, instead of fully re-creating `docker-compose.override.yml` in [patch-bitwarden.sh#L34](https://github.com/alexyao2015/BitBetter/blob/public/patch-bitwarden.sh#L34) we can use [yg](https://github.com/mikefarah/yq) to properly insert the needed lines.

For example, add the following function at the beginning of the script:
```bash
yq() {
  docker run --rm -i -v "${PWD}:/workdir" mikefarah/yq yq "$@"
}
```
Then: 
```bash
yq w $SCRIPT_BASE/bwdata/docker/docker-compose.override.yml "services.api.image" 'ghcr.io/alexyao2015/bitbetter:api-$BW_VERSION'
yq w $SCRIPT_BASE/bwdata/docker/docker-compose.override.yml "services.identity.image" 'ghcr.io/alexyao2015/bitbetter:identity-$BW_VERSION'
```

I havn't tested the above code but this is the genral idea ;)

**Comment by alexyao2015** [comment]
Great idea! Are you able to test this and submit a pr if it works?
