### ISSUE TITLE
1.41.3 breaking licenses ?

### ISSUE THREAD

**Issue by mbrackjr** [alexyao2015/BitBetter#5]
I've tried running the custom patch script that successfully upgrades to 1.41.3, but within minutes I received an email that premium license is expired.  Did anything change?

**Comment by alexyao2015** [comment]
Were you previously running the regular patch script? If so, you would need to update the licenses since they are using a different key.

**Comment by mbrackjr** [comment]
i think somehow i had a mixed install;  i've repatched with the standard script (even though i have custom keys in my bwdata/bitbetter directory that were referred to in the past, and so far no expiration messages.
